networks:
  semka:
    driver: bridge

volumes:
  postgres_data:
  pgAdmin_data:
  keycloak_data:

services:
  postgres_db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - semka
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:${DB_PORT}
  
  pgAdmin4:
    image: dpage/pgadmin4
    container_name: pgAdmin4
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgAdmin_data:/var/lib/pgadmin
    networks:
      - semka
    ports:
      - "5434:80"
  
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: ${KC_SERVER}
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      KC_DB_URL_HOST: ${DB_HOST}
      KC_DB_URL_PORT: ${DB_PORT}
      KC_DB_URL_DATABASE: ${DB_DATABASE}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_PASSWORD}
    networks:
      - semka
    volumes:
      - keycloak_data:/opt/keycloak
    ports:
      - ${KC_LOCAL_PORT}:8080
      
  pot_api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: ${API_SERVER}
    depends_on:
      postgres_db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: User ID=${DB_USER};Password=${DB_PASSWORD};Server=${DB_HOST};Port=${DB_PORT};Database=${DB_DATABASE};SearchPath=application_schema;Pooling=true
      Keycloak__Url: http://${KC_SERVER}:8080
      Keycloak__AuthorizationUrl: http://localhost:${KC_LOCAL_PORT}/realms/${KC_REALM}/protocol/openid-connect/auth
      Keycloak__MetadataAddress: http://${KC_SERVER}:8080/realms/${KC_REALM}/.well-known/openid-configuration
      Keycloak__ValidIssuer: http://localhost:${KC_LOCAL_PORT}/realms/${KC_REALM}
      Keycloak__Username: ${KC_USER}
      Keycloak__Password: ${KC_PASSWORD}
      BlazorUrl: http://${BLAZOR_SERVER}:8080
    networks:
      - semka
    ports:
      - "5000:8080"
      - "5001:8081"
  
  pot_frontend:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    container_name: ${BLAZOR_SERVER}
    depends_on:
      pot_api:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Keycloak__MetadataAddress: http://${KC_SERVER}:8080/realms/${KC_REALM}/.well-known/openid-configuration
      Keycloak__ValidIssuer: http://localhost:${KC_LOCAL_PORT}/realms/${KC_REALM}
      ApiUrl: http://${API_SERVER}:8080/
    networks:
      - semka
    ports:
      - "5002:8080"
      - "5003:8081"
