networks:
  semka:
    driver: bridge

volumes:
  postgres_data:
  pgAdmin_data:
  keycloak_data:

services:
  postgres_db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - semka
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_PASSWORD}
    networks:
      - semka
    volumes:
      - keycloak_data:/opt/keycloak
    ports:
      - "18080:8080"
      
  pot_api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: api
    depends_on:
      postgres_db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: User ID=${DB_USER};Password=${DB_PASSWORD};Server=database;Port=5432;Database=semestralka;SearchPath=application_schema;Pooling=true
      Keycloak__Url: http://keycloak:8080
      Keycloak__AuthorizationUrl: http://localhost:18080/realms/${KC_REALM}/protocol/openid-connect/auth
      Keycloak__MetadataAddress: http://keycloak:8080/realms/${KC_REALM}/.well-known/openid-configuration
      Keycloak__ValidIssuer: http://localhost:18080/realms/${KC_REALM}
      Keycloak__Username: ${KC_USER}
      Keycloak__Password: ${KC_PASSWORD}
      BlazorUrl: http://localhost:5116
    networks:
      - semka
    ports:
      - "5177:8080"
      - "5001:8081"
